# Generated by Django 4.0.3 on 2022-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=10, verbose_name='site')),
                ('dateTime', models.CharField(max_length=100, verbose_name='dateTime')),
            ],
        ),
    ]
