# Generated by Django 4.0.3 on 2022-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_rank', models.IntegerField()),
                ('b_song', models.CharField(max_length=50)),
                ('b_artist', models.CharField(max_length=50)),
                ('b_like', models.IntegerField()),
                ('b_coverImg', models.URLField()),
                ('b_date', models.DateTimeField()),
                ('b_time', models.IntegerField()),
                ('b_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Genie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_rank', models.IntegerField()),
                ('g_song', models.CharField(max_length=50)),
                ('g_artist', models.CharField(max_length=50)),
                ('g_like', models.IntegerField()),
                ('g_coverImg', models.URLField()),
                ('g_date', models.DateTimeField()),
                ('g_time', models.IntegerField()),
                ('g_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Melon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_rank', models.IntegerField()),
                ('m_song', models.CharField(max_length=50)),
                ('m_artist', models.CharField(max_length=50)),
                ('m_like', models.IntegerField()),
                ('m_coverImg', models.URLField()),
                ('m_date', models.DateTimeField()),
                ('m_time', models.IntegerField()),
                ('m_weight', models.FloatField()),
            ],
        ),
    ]
