# Generated by Django 4.0.3 on 2022-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='coverImg',
            field=models.URLField(),
        ),
    ]
