# Generated by Django 4.0.3 on 2022-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_t', models.CharField(max_length=100, verbose_name='rank_t')),
                ('title_t', models.CharField(max_length=100, verbose_name='title_t')),
                ('artist_t', models.CharField(max_length=100, verbose_name='artist_t')),
                ('img', models.CharField(max_length=100, verbose_name='img')),
                ('like', models.CharField(max_length=100, verbose_name='like')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
