# Generated by Django 4.0.3 on 2022-05-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bugs_b_date_alter_bugs_b_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='b_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='genie',
            name='g_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='melon',
            name='m_date',
            field=models.DateTimeField(),
        ),
    ]
