# Generated by Django 4.0.3 on 2022-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bugs_b_weight_alter_genie_g_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
