# Generated by Django 4.0.3 on 2022-05-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_total_rank_total_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=3000)),
            ],
        ),
    ]
